project:
  type: website

website:
  title: "Quarto_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - GreenMetric.qmd
      - Regression.qmd
      - GitSetup.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

