project:
  type: website
  output-dir: docs

website:
  title: "Quarto Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Regression.qmd
        text: Regression
      - href: GitSetup.qmd
        text: Git Setup
        menu:
          - href: exploratory.qmd
            text: Exploratory Analysis
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
